def personal_sum(*numbers):
    result=0
    incorrect_data=0
    for i in numbers:
        try:
            for j in i:
                try:
                    result+=j
                except TypeError as exc:
                    incorrect_data += 1
                    print(f'Некорректный тип данных для подсчёта суммы-{j}')
        except TypeError as exc:
            return None
        else:
            return result, incorrect_data

def calculate_average(*numbers):
    a=personal_sum(*numbers)
    saf=0
    try:
        saf=a[0]/(len(*numbers)-a[1])
    except ZeroDivisionError as exc:
        return 0
    except TypeError as exc:
        print('В numbers записан некорректный тип данных')
        return None
    else:
        return saf


print(f'Результат 1: {calculate_average("1, 2, 3")}') # Строка перебирается, но каждый символ - строковый тип
print(f'Результат 2: {calculate_average([1, "Строка", 3, "Ещё Строка"])}') # Учитываются только 1 и 3
print(f'Результат 3: {calculate_average(567)}') # Передана не коллекция
print(f'Результат 4: {calculate_average([42, 15, 36, 13])}') # Всё должно работать

